export const SHOW_SNACKBAR = 'SHOW_SNACKBAR'
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR'
export const GET_STATUS_CONNECTION = 'GET_STATUS_CONNECTION'
export const GET_METADATA_CONNECTION = 'GET_METADATA_CONNECTION'

export const DO_LOGIN = 'DO_LOGIN'
export const DO_LOGOUT = 'DO_LOGOUT'
