export const GET_STATUS_CONNECTION = 'GET_STATUS_CONNECTION'
export const GET_METADATA_CONNECTION = 'GET_METADATA_CONNECTION'

export const DO_LOGIN = 'DO_LOGIN'
export const DO_LOGOUT = 'DO_LOGOUT'

export const CREATE_LOG_AKTIVITAS = 'CREATE_LOG_AKTIVITAS'
export const GET_LOG_AKTIVITAS = 'GET_LOG_AKTIVITAS'
export const GET_LOG_PESANAN = 'GET_LOG_PESANAN'

export const GET_LIST_MENU = 'GET_LIST_MENU'
export const GET_LIST_MENU_ORDER = 'GET_LIST_MENU_ORDER'
export const GET_LIST_MENU_READY = 'GET_LIST_MENU_READY'
export const GET_ITEM_MENU = 'GET_ITEM_MENU'
export const CREATE_MENU = 'CREATE_MENU'
export const UPDATE_MENU = 'UPDATE_MENU'
export const DELETE_MENU = 'DELETE_MENU'

export const GET_NOMOR_PESANAN = 'GET_NOMOR_PESANAN'
export const GET_LIST_PESANAN = 'GET_LIST_PESANAN'
export const GET_ITEM_PESANAN = 'GET_ITEM_PESANAN'
export const CREATE_PESANAN = 'CREATE_PESANAN'
export const UPDATE_PESANAN = 'UPDATE_PESANAN'
export const DELETE_PESANAN = 'DELETE_PESANAN'
